"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronRight, FileText, Fish, Folder, Lightbulb, LockKeyhole, Mail, Maximize2, Minus, NotebookPen, Power, RotateCcw, ShieldCheck, Terminal, UserRound, Wifi, X } from "lucide-react";

type Screen = "desktop" | "mail" | "install" | "infected" | "puzzle1" | "puzzle2" | "puzzle3" | "puzzle4" | "puzzle5" | "final" | "clear";
const order: Screen[] = ["puzzle1", "puzzle2", "puzzle3", "puzzle4", "puzzle5", "final"];
const puzzleMeta = [["メールの違和感", "フィッシング"], ["連鎖する被害", "パスワード"], ["開きすぎた窓", "情報整理"], ["席を離れる前に", "物理セキュリティ"], ["ログの足跡", "調査"], ["復旧キー", "総仕上げ"]];

export default function Home() {
  const [screen, setScreen] = useState<Screen>("desktop");
  const [solved, setSolved] = useState<string[]>([]);
  const [notes, setNotes] = useState("");
  const [hint, setHint] = useState(false);
  const [toast, setToast] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [answer, setAnswer] = useState("");
  useEffect(() => { const saved = localStorage.getItem("security-training-save"); if (saved) try { const s=JSON.parse(saved); setSolved(s.solved||[]); setNotes(s.notes||""); } catch {} console.log("%cSECURITY TRAINING CONSOLE","font-size:20px;color:#56f2b3;font-weight:bold"); console.log("ヒント：怪しいメールは『さ・か・な』で確認。さ＝差出人、か＝書かれたリンク先、な＝内容の急かし方"); }, []);
  useEffect(() => { localStorage.setItem("security-training-save", JSON.stringify({solved,notes})); }, [solved,notes]);
  useEffect(() => { setHint(false); setSelected([]); setAnswer(""); }, [screen]);
  const progress=solved.length; const clock=useMemo(()=>screen==="clear"?"17:58":`17:${String(31+progress*4).padStart(2,"0")}`,[progress,screen]);
  const flash=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),2200)};
  const complete=(key:string,next:Screen,code:string)=>{if(!solved.includes(key))setSolved(v=>[...v,key]);flash(`断片コード「${code}」を回収しました`);setTimeout(()=>setScreen(next),900)};
  const checkText=(expected:string,key:string,next:Screen,code:string)=>answer.trim().toUpperCase()===expected?complete(key,next,code):flash("まだ合わないようです。画面内の手掛かりを確認してください");
  const reset=()=>{localStorage.removeItem("security-training-save");setSolved([]);setNotes("");setScreen("desktop")};
  return <main className="game-shell"><div className="desktop-bg">
    <div className="brand-mark"><ShieldCheck/> MIRAI LINK / TRAINING PC</div>
    <div className="desktop-icons"><DesktopIcon icon={<Folder/>} label="業務ファイル"/><DesktopIcon icon={<FileText/>} label="研修資料"/><button className="desk-icon" onClick={()=>setScreen("mail")}><span><Mail/></span><b>メール</b>{screen==="desktop"&&<i>1</i>}</button><button className="desk-icon" onClick={()=>setScreen("puzzle1")}><span><ShieldCheck/></span><b>復旧センター</b></button></div>
    {screen==="desktop"&&<div className="notification" onClick={()=>setScreen("mail")}><Mail/><div><strong>新着メール</strong><p>【新人研修】研修用ソフトのご案内</p></div><span>今</span></div>}
    {screen!=="desktop"&&<Window title={titleFor(screen)} danger={screen==="infected"||order.includes(screen)} onClose={()=>setScreen("desktop")}>
      {screen==="mail"&&<MailIntro onInstall={()=>setScreen("install")}/>} {screen==="install"&&<Install onDone={()=>setScreen("infected")}/>} {screen==="infected"&&<Infected onStart={()=>setScreen("puzzle1")}/>} 
      {screen==="puzzle1"&&<PuzzleOne selected={selected} setSelected={setSelected} onDone={()=>selected.length===4?complete("p1","puzzle2","7"):flash("怪しい点は4か所あります")}/>} 
      {screen==="puzzle2"&&<PuzzleTwo selected={selected} setSelected={setSelected} answer={answer} setAnswer={setAnswer} onDone={()=>selected.length===3?checkText("REUSE","p2","puzzle3","K"):flash("同じパスワードの3サービスを選んでください")}/>} 
      {screen==="puzzle3"&&<PuzzleThree answer={answer} setAnswer={setAnswer} onDone={()=>checkText("LINK","p3","puzzle4","2")}/>} 
      {screen==="puzzle4"&&<PuzzleFour selected={selected} setSelected={setSelected} onDone={()=>selected.length===4?complete("p4","puzzle5","F"):flash("対応が必要なものは4つです")}/>} 
      {screen==="puzzle5"&&<PuzzleFive answer={answer} setAnswer={setAnswer} onDone={()=>checkText("0918","p5","final","A")}/>} 
      {screen==="final"&&<FinalPuzzle answer={answer} setAnswer={setAnswer} onDone={()=>checkText("7K2FA","final","clear","RESTORE")}/>} {screen==="clear"&&<Clear solved={solved} onReset={reset}/>} 
    </Window>}
    {order.includes(screen)&&<aside className="mission-panel"><div className="mission-head"><span>RECOVERY</span><b>{progress}/6</b></div><div className="segments">{[0,1,2,3,4,5].map(i=><i key={i} className={i<progress?"done":""}/>)}</div><p>復旧キー断片</p><strong>{["7","K","2","F","A"].map((x,i)=><span key={i}>{i<progress?x:"•"}</span>)}</strong><button onClick={()=>setHint(v=>!v)}><Lightbulb/>ヒント</button>{hint&&<small>{hintFor(screen)}</small>}</aside>}
    <button className="memo-toggle" onClick={()=>document.querySelector(".memo")?.classList.toggle("open")}><NotebookPen/>メモ</button><aside className="memo"><header><NotebookPen/>調査メモ<button onClick={()=>document.querySelector(".memo")?.classList.remove("open")}><X/></button></header><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="見つけた文字や気づいたことを自由に記録…"/><p>この端末内だけに自動保存されます</p></aside>
    <footer className="taskbar"><button className="start"><ShieldCheck/></button><button onClick={()=>setScreen("mail")}><Mail/></button><button onClick={()=>setScreen("puzzle1")}><ShieldCheck/></button><div/><Wifi/><span>JPN<br/><b>{clock}</b></span><Power/></footer>{toast&&<div className="toast"><Check/>{toast}</div>}
  </div></main>;
}

function DesktopIcon({icon,label}:{icon:React.ReactNode,label:string}){return <div className="desk-icon"><span>{icon}</span><b>{label}</b></div>}
function Window({title,danger,children,onClose}:{title:string,danger?:boolean,children:React.ReactNode,onClose:()=>void}){return <section className={`app-window ${danger?"danger":""}`}><header><div className="app-dot"/><strong>{title}</strong><span/><button><Minus/></button><button><Maximize2/></button><button onClick={onClose}><X/></button></header><div className="window-body">{children}</div></section>}
function titleFor(s:Screen){return ({mail:"MIRAI Mail",install:"Training Software Installer",infected:"SYSTEM RECOVERY",puzzle1:"調査 01 / メール",puzzle2:"調査 02 / アカウント",puzzle3:"調査 03 / 異常ウィンドウ",puzzle4:"調査 04 / デスク",puzzle5:"調査 05 / ログ",final:"最終復旧",clear:"RECOVERY COMPLETE",desktop:""} as Record<Screen,string>)[s]}
function hintFor(s:Screen){return ({puzzle1:"F12を押して開発者ツールのConsoleも確認してみましょう。",puzzle2:"同じ文字列が設定された3サービスを選び、危険を表す英単語を入力。",puzzle3:"小窓を時刻順に並べ、強調された文字を読んでください。",puzzle4:"他人に見られる・使われる・持ち去られると困るものを選びます。",puzzle5:"不審ログインの直前、認証情報を入力した時刻は？",final:"集めた断片を、問題を解いた順に入力します。"} as Record<string,string>)[s]||""}
function MailIntro({onInstall}:{onInstall:()=>void}){return <div className="mail-layout"><nav><b>受信トレイ</b><span>スター付き</span><span>送信済み</span></nav><article><div className="mail-subject"><p>【新人研修】研修用ソフトのご案内</p><small>研修事務局 &lt;training@mirai-link.example&gt;</small></div><p>中村さん</p><p>本日のセキュリティ研修で使用するアプリをご案内します。下のボタンからインストールし、17:30までに開始してください。</p><button className="primary" onClick={onInstall}>研修用ソフトをインストール <ChevronRight/></button><div className="attachment"><FileText/><span>security_training_setup.exe<small>12.4 MB</small></span></div></article></div>}
function Install({onDone}:{onDone:()=>void}){const[n,setN]=useState(0);useEffect(()=>{const t=setInterval(()=>setN(v=>v>=100?100:v+4),70);return()=>clearInterval(t)},[]);return <div className="center-card"><ShieldCheck className="big-icon"/><h1>セキュリティ研修</h1><p>{n<100?"研修環境を準備しています…":"インストールが完了しました"}</p><div className="loadbar"><i style={{width:`${n}%`}}/></div><b>{n}%</b>{n===100&&<button className="primary" onClick={onDone}>アプリを開く</button>}</div>}
function Infected({onStart}:{onStart:()=>void}){return <div className="infection"><AlertTriangle/><p className="eyebrow">SECURITY INCIDENT / 17:31</p><h1>端末がロックされました</h1><p>研修用ファイルを装った不正なプログラムが実行されました。<br/>復旧キーは、端末内に残された6つの調査記録から再構成できます。</p><div className="countdown"><small>自動初期化まで</small><b>00:29:59</b></div><button className="primary red" onClick={onStart}>調査を開始する <ChevronRight/></button><small>※これは安全に設計された研修用の演出です。実際のウイルス動作は行いません。</small></div>}
function PuzzleFrame({tag,title,lead,children,onDone}:{tag:string,title:string,lead:string,children:React.ReactNode,onDone:()=>void}){return <div className="puzzle"><p className="eyebrow">{tag}</p><h1>{title}</h1><p className="lead">{lead}</p>{children}<button className="primary solve" onClick={onDone}>回答を確定する <ChevronRight/></button></div>}
function PuzzleOne({selected,setSelected,onDone}:{selected:string[],setSelected:(x:string[])=>void,onDone:()=>void}){const opts=[["sender","差出人：研修事務局 <training@mirai-Iink.example>"],["rush","5分以内に確認しないと全データを削除します"],["url","表示URL：portal.mirai.example / 実際：verify-mirai.example"],["file","添付：employee_list.zip.exe"]];const toggle=(x:string)=>setSelected(selected.includes(x)?selected.filter(v=>v!==x):[...selected,x]);return <PuzzleFrame tag="CASE 01 / PHISHING" title="釣られる前に、違和感を釣り上げろ" lead="研修メールの再現画面です。怪しい点を4つ選んでください。" onDone={onDone}><div className="phish-card"><div className="fish-badge"><Fish/>「さ・か・な」で確認</div>{opts.map(([k,v])=><button key={k} className={selected.includes(k)?"selected":""} onClick={()=>toggle(k)}>{v}<Check/></button>)}</div></PuzzleFrame>}
function PuzzleTwo({selected,setSelected,answer,setAnswer,onDone}:{selected:string[],setSelected:(x:string[])=>void,answer:string,setAnswer:(s:string)=>void,onDone:()=>void}){const rows=[["勤怠管理","BlueBird26!"],["社内ポータル","BlueBird26!"],["ファイル共有","BlueBird26!"],["会議予約","Desk#8194"]];const toggle=(x:string)=>setSelected(selected.includes(x)?selected.filter(v=>v!==x):[...selected,x]);return <PuzzleFrame tag="CASE 02 / PASSWORD" title="1つの鍵が、3つの扉を開けていた" lead="実際のパスワードは入力しません。架空アカウントから危険な3サービスを選択してください。" onDone={onDone}><div className="account-list">{rows.map(([a,p])=><button key={a} onClick={()=>toggle(a)} className={selected.includes(a)?"selected":""}><UserRound/><span><b>{a}</b><small>社員ID：NKM-042</small></span><code>{p}</code><Check/></button>)}</div><label className="answer-field">この危険を表す英単語（画面下の用語集を参照）<input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="5文字"/><small>用語集：使い回し = REUSE ／ 強化 = HARDEN</small></label></PuzzleFrame>}
function PuzzleThree({answer,setAnswer,onDone}:{answer:string,setAnswer:(s:string)=>void,onDone:()=>void}){const cards=[["09:12","L","メールを受信"],["09:16","I","リンクをクリック"],["09:18","N","認証情報を入力"],["09:24","K","不審ログイン発生"]];return <PuzzleFrame tag="CASE 03 / WINDOWS" title="開きすぎた窓が、ひとつの言葉を残した" lead="大量に開いた警告ウィンドウを時刻順に読み、中央の文字をつなげてください。" onDone={onDone}><div className="window-pile">{cards.map((c,i)=><div key={c[0]} style={{transform:`translate(${i%2?18:-18}px,${i*3}px) rotate(${i%2?1:-1}deg)`}}><header>warning_{i+1}.log <X/></header><p><small>{c[0]}</small><b>{c[1]}</b><span>{c[2]}</span></p></div>)}</div><label className="answer-field">並び替えてできる4文字<input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="____"/></label></PuzzleFrame>}
function PuzzleFour({selected,setSelected,onDone}:{selected:string[],setSelected:(x:string[])=>void,onDone:()=>void}){const items=[["pc","ロックされていないPC","Win + L"],["doc","顧客名簿","引き出しへ"],["card","社員証","携帯する"],["memo","パスワード付箋","安全に処分"],["pen","ボールペン","そのまま"],["cup","空のマグカップ","そのまま"]];const toggle=(x:string)=>setSelected(selected.includes(x)?selected.filter(v=>v!==x):[...selected,x]);return <PuzzleFrame tag="CASE 04 / CLEAN DESK" title="10分の離席。そのままで大丈夫？" lead="他人に見られたり、使われたりすると危険な4つを選び、安全な状態にしてください。" onDone={onDone}><div className="desk-grid">{items.map(([k,n,a])=><button key={k} className={selected.includes(k)?"selected":""} onClick={()=>toggle(k)}><span>{k==="pc"?"💻":k==="doc"?"📄":k==="card"?"🪪":k==="memo"?"📝":k==="pen"?"🖊️":"☕"}</span><b>{n}</b><small>{selected.includes(k)?a:"クリックして対応"}</small></button>)}</div></PuzzleFrame>}
function PuzzleFive({answer,setAnswer,onDone}:{answer:string,setAnswer:(s:string)=>void,onDone:()=>void}){return <PuzzleFrame tag="CASE 05 / LOG" title="侵入は、いつ始まった？" lead="不審ログインの直前に起きた出来事を追い、認証情報を入力した時刻を4桁で入力してください。" onDone={onDone}><div className="log-view"><Terminal/><code><span>09:12</span> MAIL_RECEIVED<br/><span>09:16</span> EXTERNAL_LINK_OPENED<br/><mark><span>09:18</span> CREDENTIAL_FORM_SUBMITTED</mark><br/><span>09:21</span> LOGIN_SUCCESS / JP<br/><b><span>09:24</span> LOGIN_ALERT / UNKNOWN</b><br/><span>12:25</span> NETWORK_CHANGED</code></div><label className="answer-field">時刻（例：0912）<input value={answer} onChange={e=>setAnswer(e.target.value.replace(/\D/g,""))} maxLength={4} placeholder="0000"/></label></PuzzleFrame>}
function FinalPuzzle({answer,setAnswer,onDone}:{answer:string,setAnswer:(s:string)=>void,onDone:()=>void}){return <PuzzleFrame tag="FINAL / RESTORE KEY" title="復旧キーを完成させろ" lead="各調査で回収した5つの断片を、調査した順番につなげてください。" onDone={onDone}><div className="key-slots">{["7","K","2","F","A"].map((x,i)=><span key={i}>{x}<small>CASE {i+1}</small></span>)}</div><label className="answer-field">5文字の復旧キー<input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="_____"/></label><div className="security-note"><LockKeyhole/><p><b>パスワード使い回しが被害を拡大させました</b><br/>偽サイトで知られた1つのパスワードから、同じ文字列を使っていた勤怠・ポータル・共有フォルダまで危険になりました。</p></div></PuzzleFrame>}
function Clear({solved,onReset}:{solved:string[],onReset:()=>void}){return <div className="clear-screen"><div className="shield-ring"><ShieldCheck/></div><p className="eyebrow">MISSION COMPLETE / 17:58</p><h1>端末の復旧に成功しました</h1><p>被害の原因は「偽の研修メール」と「パスワードの使い回し」。<br/>あなたの判断で、被害の拡大を止めることができました。</p><div className="report"><h2>あなたが身につけた防御</h2>{puzzleMeta.map((p,i)=><div key={p[0]}><Check/><span><b>{p[0]}</b><small>{p[1]}</small></span><em>{i<solved.length?"CLEAR":"—"}</em></div>)}</div><div className="final-advice"><b>現実の職場では</b><p>不審なファイルを開いたら、自分だけで復旧しようとせず、ネットワークを切断して情報システム部門へすぐ報告しましょう。</p></div><button className="secondary" onClick={onReset}><RotateCcw/>最初からプレイ</button></div>}
